### ISSUE TITLE
Create N1QL indexes for newly created collections

### ISSUE THREAD

**Issue by MikeGoldsmith** [couchbaselabs/VSCode-Couchbase#101]
**Is your feature request related to a problem? Please describe.**
You need a n1ql index to query collections and this should be automatically created when creating a new collection.

#100 added support for detecting missing indexes and prompt the user to create one

**Describe the solution you'd like**
Indexes are created when creating a new collection using the extension - either automatically or prompt the user.

**Comment by deniswsrosa** [comment]
The new versions of couchbase will come with an internal index that will allow queries to run without an index. Kush did a fix that tries to run a query, and then if it fails because of a missing index, we show a message to the user asking if he wants to create an index.
