### ISSUE TITLE
Connection to bucket should use Wan Development Profile

### ISSUE THREAD

**Issue by deniswsrosa** [couchbaselabs/VSCode-Couchbase#121]
**Is your feature request related to a problem? Please describe.**
The connection to the bucket should be using the configProfile "wanDevelopment". Ex:

```
 const cluster = await couchbase.connect(clusterConnStr, {
    username: username,
    password: password,
    // Sets a pre-configured profile called "wanDevelopment" to help avoid latency issues
    // when accessing Capella from a different Wide Area Network
    // or Availability Zone (e.g. your laptop).
    configProfile: 'wanDevelopment',
  })
```
https://docs.couchbase.com/nodejs-sdk/current/hello-world/start-using-sdk.html

The networking on the user's notebook might be unstable. This profile helps to deal with such scenarios

**Comment by AayushTyagi1** [comment]
@deniswsrosa 
I have tried that but the connection was failing when using WAN Development Profile but it was not connection with it. 
I will try again.
