### ISSUE TITLE
No Option to delete an active connection

### ISSUE THREAD

**Issue by deniswsrosa** [couchbaselabs/VSCode-Couchbase#138]
![Screen Shot 2023-03-14 at 6 16 17 PM](https://user-images.githubusercontent.com/216006/225085611-2f238a3b-defb-44f0-b0fc-a1ed90966130.png)

There is no option to delete a connection. Don't forget to ask the user for confirmation of this operation

**Comment by AayushTyagi1** [comment]
A cluster with an active connection can not be deleted. Only the cluster which is disconnected have a delete option.
![image](https://user-images.githubusercontent.com/42893909/225200135-80014440-c949-46be-af87-26f3461ad4f9.png)

**Comment by deniswsrosa** [comment]
@AayushTyagi1  What happens if I just have one connection? Then I can't delete it? Do I need to create a new one just to delete the one I wanted?
If the connection is active, then the "delete" option must disconnect the cluster and delete it.

**Comment by AayushTyagi1** [comment]
@deniswsrosa In case of single connection or if you want to delete an active cluster You can disconnect the cluster and then delete it. 
However we can provide an option to delete an active cluster as well.

**Comment by deniswsrosa** [comment]
@AayushTyagi1 I would prefer that we offer this option. It wasn't clear to me that you had to disconnect, as I only had one connection there. Delete an active connection also seems to be a common thing in other tools.
