### ISSUE TITLE
Allow documents to viewed from bucket and scope level

### ISSUE THREAD

**Issue by MikeGoldsmith** [couchbaselabs/VSCode-Couchbase#14]
**Is your feature request related to a problem? Please describe.**
Currently it's only possible to list and view documents at the collection level. It is desireable to allow documents to be viewed at the bucket (all scopes & collections) and scope level (all collections).

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

_Please delete paragraphs that you did not use before submitting._

**Comment by deniswsrosa** [comment]
@AayushTyagi1 Could you please double-check that we can see documents in the default scope and default collection? That should be good enough for this one

**Comment by AayushTyagi1** [comment]
@deniswsrosa We can only access documents under a particular collection (we need to select a particular collection) even in default bucket and default scope.
