### ISSUE TITLE
Connection string should not contain scheme, but "use secure" checkbox

### ISSUE THREAD

**Issue by roikatz** [couchbaselabs/VSCode-Couchbase#162]
**Is your feature request related to a problem? Please describe.**
Currently, when you are connecting to a server you need to have the scheme, which basically only define if the connection is secured or not. 

**Describe the solution you'd like**
Scheme is not needed here, to make it more streamlined, all we need is the connection string and a checkbox, whether to use secure or not.

**Additional context**
<img width="582" alt="image" src="https://user-images.githubusercontent.com/9395306/229986434-2d0ea511-3696-4fde-8744-fa7c7f750d99.png">

**Comment by deniswsrosa** [comment]
Also, If the user enters a connection string with couchbase:// or couchbases:// we should remove it.

**Comment by AayushTyagi1** [comment]
> Also, If the user enters a connection string with couchbase:// or couchbases:// we should remove it.

Could you please elaborate?
