### ISSUE TITLE
Cannot type bucket names with lower case 'k' in it

### ISSUE THREAD

**Issue by vijaygopal-couchbase** [couchbaselabs/VSCode-Couchbase#184]
I was able to connect to Couchbase cluster and when I tried use SQL++ notebook against 'BackToWork' bucket, I was unable to enter letter 'k' in smaller case. I am able to enter upper case K but not lower case.
<img width="874" alt="image" src="https://user-images.githubusercontent.com/62717469/233186810-bdf197d9-93d5-4cf7-adb8-04a4a39620f0.png">

**Comment by AayushTyagi1** [comment]
Hey @vijaygopal-couchbase ,
I am not able to regenerate this issue but we will be releasing the new version next weak where you can see logging window which will show the exact error you are facing so that we would be able to figure out the exact cause of this.
