### ISSUE TITLE
Refresh bucket

### ISSUE THREAD

**Issue by MikeGoldsmith** [couchbaselabs/VSCode-Couchbase#22]
**Is your feature request related to a problem? Please describe.**
With a connect cluster, a user should be able to refresh an existing bucket to get updated scopes, collections and documents.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

_Please delete paragraphs that you did not use before submitting._

**Comment by AayushTyagi1** [comment]
@MikeGoldsmith 
There is an option on bucket to refresh scopes which is doing the same job as this. 
Can you please elaborate this issue?
Should we rename refresh scopes to refresh bucket because I can see it is refreshing the scopes and collection under this.
