### ISSUE TITLE
Add Bucket administrative information 

### ISSUE THREAD

**Issue by roikatz** [couchbaselabs/VSCode-Couchbase#34]
**Is your feature request related to a problem? Please describe.**
Currently the VS CODE is only showing the documents inside bucket and collections (the the count), but it would be useful to get some additional information about the bucket, like quota, number of replicas, compression and etc, as a UI replacement for the tech savvy.

**Describe the solution you'd like**
Add an additional tree entry, with bucket/scope/collection configuration data.

**Describe alternatives you've considered**
Currently the main easy alternative is the Couchbase Admin UI.

**Comment by deniswsrosa** [comment]
@AayushTyagi1 add on option called "Info" when the user right click on the bucket.
