### ISSUE TITLE
Show the "Accept Terms and Conditions" dialog in the plugin

### ISSUE THREAD

**Issue by deniswsrosa** [couchbaselabs/VSCode-Couchbase#359]
Implement similar behavior of this ticket https://github.com/couchbaselabs/couchbase_jetbrains_plugin/issues/181

**Comment by prajwal-pai77** [comment]
Closing via: https://github.com/couchbaselabs/VSCode-Couchbase/commit/7f6aa1bcb3944712b7d966049364491cd3ad525a
