### ISSUE TITLE
Add ability to view document's metadata

### ISSUE THREAD

**Issue by roikatz** [couchbaselabs/VSCode-Couchbase#36]
**Is your feature request related to a problem? Please describe.**
Currently, it's impossible to view document's metadata which is useful, for CAS, expiration or xattrs examination 

**Describe the solution you'd like**
Add a context menu on the document to view the document's metadata (xattrs keys/metadata)

**Describe alternatives you've considered**
Admin UI or N1QL

**Comment by deniswsrosa** [comment]
Kush:
The flow should be the following:

- Right-click on the document
-  Click on "show metadata". (which opens the editor with the document metadata)
- when the document is saved, the metadata should be updated

(we don't need to show the metadata in the tree, as the scenarios using it are a little bit less common)
