### ISSUE TITLE
Named and Positional Parameter Support for VSCode Workbench Query Files

### ISSUE THREAD

**Issue by amfrye777** [couchbaselabs/VSCode-Couchbase#379]
**Is your feature request related to a problem? Please describe.**
In order to use the VSCode extension as a primary development tool, I need the ability to pass in values for parameters. Nearly all application queries will require at least one input parameter, and it is not helpful to have to hardcode values directly inline of a query. Then in order to commit the query back into source control - have to replace all those hardcoded values back to parameter syntax. 

**Describe the solution you'd like**
Review the functionality provided by the Query Workbench in Couchbase Server UI. 
**MVP Feature Set:** Named and Positional Parameter Support for VSCode Workbench Query Files.
Ideal solution would be to be able to supply a JSON object containing all desired parameter values. Maybe some way to connect a workbench to a local .json file as configuration or some other solution.

**Additional context**
Couchbase Server Query Workbench Options:
![image](https://github.com/couchbaselabs/VSCode-Couchbase/assets/19143491/ffaf46d5-6614-4e13-b2f8-02b30384b228)

**Comment by deniswsrosa** [comment]
Hi,
We were uncertain about how often users use this feature. Thanks for the feedback, we will implement it in the next releases.

**Comment by amfrye777** [comment]
@lokesh-couchbase 
Moving my followup to the correct issue.

> @amfrye777 We will release the KV range queries and the named parameters for **Jebrains** early next week. The same features for VSCode are coming a couple of days later.

What was the chosen implementation for named parameters? some form of configuration file attached to the workbench? did any of the other settings from the screenshot get included as well?

**Comment by lokesh-couchbase** [comment]
So we will have 2 places for named parameters.
1st will be a root level file which you can share among your team just like a .env file.
2nd will be a UI based VSCode specific named parameter which you may set. These cannot be shared. However this will be prioritised in case of same parameter.

Other fields will require a bit more thought before implementing but as of now we don't support it. If you have any particular field which you believe will get extensively used, drop the comment here and we can prioritise it.

For now, we also will not add Positional Params.

**Comment by amfrye777** [comment]
> Still under design phase but this is what we propose. So we will have 2 places for named parameters. 1st will be a root level file which you can share among your team just like a .env file. 2nd will be a UI based VSCode specific named parameter which you may set. These cannot be shared. However this will be prioritised in case of same parameter.
> 
> Other fields will require a bit more thought before implementing but as of now we don't support it. If you have any particular field which you believe will get extensively used, drop the comment here and we can prioritise it.
> 
> For now, we also will not add Positional Params.

@lokesh-couchbase 

Screenshots or instructions regarding how to work with the named parameters in both approaches mentioned above would be helpful. I'm not sure how to add.
