### ISSUE TITLE
Provide a way to perform a direct KV Document Lookup on a collection by providing a document key string

### ISSUE THREAD

**Issue by amfrye777** [couchbaselabs/VSCode-Couchbase#380]
**Is your feature request related to a problem? Please describe.**
The current Bucket/Scope/Collection tree is great for navigation and provides some sample documents. 
Currently, a primary form of data research / troubleshooting / development for finding documents for my team is to use the "Documents" tab. From my review on the VSCode extension, there is no way to specify a specific document to retrieve by passing a string key.

**Describe the solution you'd like**
**MVP Feature:** On the "Right Click" menu for a collection in the Bucket/Scope/Collection tree, provide an option for "Key Lookup" allowing entry for a specific document Key.
**Nice To Have:** Provide an option more similar to the Couchbase Server UI - where you can retrieve documents based on a range, allowing entry of "Key Starts With "XXX" and "Key Ends With "YYY"

**Additional context**
Couchbase Server Documents Tab
![image](https://github.com/couchbaselabs/VSCode-Couchbase/assets/19143491/04ad7ffd-1a89-4c91-b335-4d7c672ef3d3)
Key Range for Starts/Ends With
![image](https://github.com/couchbaselabs/VSCode-Couchbase/assets/19143491/f4354584-508a-4ab8-afb1-c5172d4c464f)

**Comment by deniswsrosa** [comment]
Hi,
Thank you for your feedback. This is indeed a missing feature, we will work on it asap.

**Comment by lokesh-couchbase** [comment]
Hi, so for single document opening we provide "Open Document" functionality 

<img width="175" alt="Screenshot 2024-05-23 at 7 21 35 PM" src="https://github.com/couchbaselabs/VSCode-Couchbase/assets/113521973/ed3083a2-b81d-4935-9f89-9ee55febbe97">

For Range Based Filtering , we now support both query based filtering (using SQL++ where statements) and KV based (start to end document IDs)
<img width="429" alt="image" src="https://github.com/couchbaselabs/VSCode-Couchbase/assets/113521973/fb10e6e1-a36f-46f3-bff4-a92012c46279">

It's in development branch (FC) and will been released to production soon.

Thanks for the feature request

**Comment by amfrye777** [comment]
I look forward to testing this out! A nice quick turnaround as well!

**Comment by deniswsrosa** [comment]
@amfrye777 We will release the KV range queries and the named parameters for **Jebrains** early next week. The same features for VSCode are coming a couple of days later.

**Comment by lokesh-couchbase** [comment]
@amfrye777 Added support for KV Range type Document Filter.
