### ISSUE TITLE
Allow configurable file extension types that will be recognized by the workbench features

### ISSUE THREAD

**Issue by amfrye777** [couchbaselabs/VSCode-Couchbase#393]
**Is your feature request related to a problem? Please describe.**
We have query files stored in our solution as `.n1ql`. We would like to be able to use the workbench extension inline of our code repo for all of these files. The only way to accomplish this today is to alter the extension during development to `.sqlpp` to gain access to the workbench features, then modify the extension back to .n1ql like our application expects them to be. 

**Describe the solution you'd like**
Add an extension option for a configurable extension type (ideally, a comma separated list of values so we can do something like `.sqlpp, .sql, .n1ql` )

**Describe alternatives you've considered**
We can work around this by modifying the extension of a query file to `.sqlpp` when we want to run a query. Ideally, we can avoid having to take on the risk of altering code to accept the `.sqlpp` extension and modifying all query files in our app and any accidental check-ins that modify the file types.

**Comment by deniswsrosa** [comment]
Hi,

We will also add support for the ".n1ql" extension but making it configurable is something tricky. The IDE expects a fixed extension type to select which editor should be used.

**Comment by lokesh-couchbase** [comment]
We are adding support for n1ql files. Now you can have all workbench features right inside .n1ql files. Just note creating a new workbench from extension will still result in sqlpp file format. You can still manually create files.

The update should be released next week

**Comment by lokesh-couchbase** [comment]
@amfrye777 , We have released version 2.0.4 with .n1ql files support.

Please do try it out and we will be waiting for more feedbacks from you
