### ISSUE TITLE
Cannot create vsix file due to src/test/runTest.ts

### ISSUE THREAD

**Issue by BabarKhanDev** [couchbaselabs/VSCode-Couchbase#74]
**Describe the bug**
when running `vsce package` you get the following error:
```
ERROR in VSCode-Couchbase/src/test/runTest.ts(19,26)
      TS2307: Cannot find module 'vscode-test' or its corresponding type declarations.
```
This prevents a vsix file from being generated

**Steps to reproduce**
Navigate to the main branch and run `vsce package`

**What did you expect to see?**
A vsix file should be produced

**What did you see instead?**
no vsix file

**What version did you use?**
VSCode Version: 1.70.1 (Universal)
Extension Version: v0.4.0 - note I commented out the problematic code to make the 0.4.0 release but it should still be in the github repo

**Comment by mikereiche** [comment]
work-around is to comment anything that references vscode-test in runTest.ts

**Comment by mikereiche** [comment]
It should be :

 import { runTests } from "@vscode/test-electron";

**Comment by MikeGoldsmith** [comment]
This wasn't a known issue, it was something that accidentally broke during some dependency updates and was not reported until recently. We created this issue once we found the problem and used your suggestion to fix it (thanks).

**Comment by mikereiche** [comment]
sorry - posted on the wrong issue.
