### ISSUE TITLE
vsce package needs webpack 

### ISSUE THREAD

**Issue by mikereiche** [couchbaselabs/VSCode-Couchbase#78]
michaelreiche@HQML0612s-MBP VSCode-Couchbase

**Describe the bug**
needs webpack 

**Steps to reproduce**
 % vsce package       
Executing prepublish script 'npm run vscode:prepublish'...

> vscode-couchbase@0.4.0 vscode:prepublish
> webpack --devtool source-map

sh: webpack: command not found
 ERROR  npm failed with exit code 127

**What did you expect to see?**
no error

**What did you see instead?**
sh: webpack: command not found
 ERROR  npm failed with exit code 127

**What version did you use?**
main. I think it's 0.4 right now.

**Additional context**
On MacOs.
Solution is to install webpack.

  brew install webpack

**Comment by deniswsrosa** [comment]
@MikeGoldsmith  is this one solved already?

**Comment by MikeGoldsmith** [comment]
Not yet, we just need to add to the README to say it's a required tool to build the VCSE package.

**Comment by deniswsrosa** [comment]
Fixed
