### ISSUE TITLE
extension commands fail with :  command 'vscode-couchbase.createClusterConnection' not found

### ISSUE THREAD

**Issue by mikereiche** [couchbaselabs/VSCode-Couchbase#81]
**Describe the bug**
extension commands fail with :

command 'vscode-couchbase.createClusterConnection' not found

command 'vscode-couchbase.refreshConnection' not found

**Steps to reproduce**
Install the extension, click on +

**What did you expect to see?**
A clear and concise description of what you expected to see.

**What did you see instead?**
A clear and concise description of what you saw instead.

**What version did you use?**
VSCode Version:
Extension Version:

**Additional context**

**Comment by mikereiche** [comment]
Maybe remove the UI widgets until they are working.

**Comment by MikeGoldsmith** [comment]
Hi @mikereiche - these commands do work as long as you have a local binding file that CB Node SDK can use to to work with lcb. The VSCE package does include a amd64 binding file and we're working on improving that for all platforms / node versions.

**Comment by mikereiche** [comment]
Thanks.   What is nice to do for known issues is create an issue for it and then close it if there is a solution.   Then when someone hits that issue they will find it when searching for it.
