### ISSUE TITLE
Handle missing indexes for collections & scopes

### ISSUE THREAD

**Issue by MikeGoldsmith** [couchbaselabs/VSCode-Couchbase#9]
**Describe the bug**
Indexes are not automatically created for collections and scopes which means that cannot be queired easily. The extension should detect and handle a missing indexes, informing the user why.

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

**What did you expect to see?**
A clear and concise description of what you expected to see.

**What did you see instead?**
A clear and concise description of what you saw instead.

**What version did you use?**
VSCode Version:
Extension Version:

**Additional context**

**Comment by deniswsrosa** [comment]
This one has already been solved by Kush
